### ISSUE TITLE
can you modify the extends activity to appcompatactivity and modify the res v4 to none?

### ISSUE THREAD

**Issue by jiqimaogou** [yayaa/TheActivityManager#1]
can you modify the baseactivity extends activity the appcompatactivity?
and
remove the res directory, the mipmap-hdpi-v4 is confict mipmap-hdpi

**Comment by yayaa** [comment]
You don't have to use that base activity, you could've just created yours. But since AppCompatActivity is the new/right way, i updated my library. And removed res folder completely... So you can use it as below:
     compile 'com.yayandroid:TheActivityManager:1.0.2'
