### ISSUE TITLE
getCurrentActivity has a bug

### ISSUE THREAD

**Issue by jiqimaogou** [yayaa/TheActivityManager#2]
if we have a A activity, in it's onResume method we call getCurrentActivity

```
public void onResume() {
    TheActivityManger.getInstance().getCurrentActivity();
}
```

and A start B, and then B finish, the currentActivity is still B. because before call B onDestroy, A is call onResume.

**Comment by yayaa** [comment]
As you are in onResume method of your A activity, you could simply call "this" instead of the library, but yes you're right. I modified the library, so you can include version 1.0.3 to getCurrentActivity correct.
