### ISSUE TITLE
It may cause memory leak 

### ISSUE THREAD

**Issue by qihigh** [yayaa/TheActivityManager#3]
I read the code, it seems `TheActivityManager` has hold all activities's reference which cannot be free by system gc .

**Comment by yayaa** [comment]
Since you call corresponding methods in Activity's lifecycle, it shouldn't.

**Comment by tinybright** [comment]
Will it  cause memory leak?

**Comment by yayaa** [comment]
I just test it with LeakCanary and there is no leak, also updated sample project as LC included.

**Comment by tinybright** [comment]
I test with android studio.
It's strange. There are serval instances in memory.But it says that there is no leak.
![3](https://cloud.githubusercontent.com/assets/8720949/13738717/c783c74c-ea01-11e5-9a08-d169ccf0fecf.png)
![4](https://cloud.githubusercontent.com/assets/8720949/13738718/c78f125a-ea01-11e5-9462-d27382e7fefd.png)

**Comment by yayaa** [comment]
Yes, because library works as keeping static instances but it keeps in order, so whenever you move back it'll release that instance as well. So GC can still release that memory. As Long as you call onPause and onDestroy there shouldn't be any leak.
