### ISSUE TITLE
Finish all activities except current or specific activity?

### ISSUE THREAD

**Issue by khaledkhj** [yayaa/TheActivityManager#6]
Such a good library.

Could we have the ability to finish all activity expect specific one, similar to "toLanding()", but this could be helpful to clear all previous activities except current one.

Thanks.

**Comment by yayaa** [comment]
Wouldn't [`toInstanceOf`](https://github.com/yayaa/TheActivityManager/blob/master/library/app/src/main/java/com/yayandroid/theactivitymanager/TheActivityManager.java#L352) do the trick?

**Comment by khaledkhj** [comment]
No, I don't think.

What I need in my case is that I want to run for example HOME for the first time and clear all previous activities (I went through 3 as an example)!!

toInstanceOf works if the activity is already there and ran if I am not mistaken!

**Comment by yayaa** [comment]
Then you don't even need anything :)

```java
TheActivityManager.finishAll();
startActivity(HOME)
```
